# Node.js with webpack
# Build a Node.js project using the webpack CLI.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

#name: $(Major).$(Minor).$(Rev:r)
name: _$(Major).$(Minor).$(rev:r)

stages:
- stage: build
  displayName: 'Build'
  jobs:
  - job: run_build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - task: TfxInstaller@2
      inputs:
        version: 'v0.6.x'
    - task: Npm@1
      inputs:
        command: 'install'
  # Prod First
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: |
          **\*.ts
        FindRegex: '__INSTRUMENTATIONKEY__'
        ReplaceRegex: '$(TelemetryKey)'
        UseUTF8: false
        UseRAW: true
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        publisherId: '$(PublisherId)'
        extensionId: '$(ExtensionId)'
        extensionVersion: '$(Build.BuildNumber)'
        updateTasksVersion: true
        updateTasksId: true
        extensionVisibility: 'private'
        extensionPricing: 'free'

# QA Second
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: |
          **\*.ts
        FindRegex: '__INSTRUMENTATIONKEY__'
        ReplaceRegex: '$(TelemetryKey-QA)'
        UseUTF8: false
        UseRAW: true
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: 'vss-extension.json'
        FindRegex: '"description": "'
        ReplaceRegex: '"description": "QA: '
        UseUTF8: false
        UseRAW: true
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: 'vss-extension.json'
        FindRegex: '"name": "'
        ReplaceRegex: '"name": "QA: '
        UseUTF8: false
        UseRAW: true
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: |
          **\menu.ts
          **\menu.js
        FindRegex: '"Add Property Widget to dashboard"'
        ReplaceRegex: '"QA: Add Property Widget to dashboard"'
        UseUTF8: false
        UseRAW: true
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        publisherId: '$(PublisherId)'
        extensionId: '$(ExtensionId)'
        extensionVersion: '$(Build.BuildNumber)'
        extensionTag: '-QA'
        updateTasksVersion: true
        extensionVisibility: 'private'
        extensionPricing: 'free'

# DEV Third
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: |
          **\*.ts
        FindRegex: '__INSTRUMENTATIONKEY__'
        ReplaceRegex: '$(TelemetryKey-DEV)'
        UseUTF8: false
        UseRAW: true
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'run build'
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: 'vss-extension.json'
        FindRegex: '"description": "QA:'
        ReplaceRegex: '"description": "DEV: '
        UseUTF8: false
        UseRAW: true
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: 'vss-extension.json'
        FindRegex: '"name": "QA:'
        ReplaceRegex: '"name": "DEV: '
        UseUTF8: false
        UseRAW: true
    - task: RegexReplace@3
      inputs:
        InputSearchPattern: |
          **\menu.ts
          **\menu.js
        FindRegex: '"QA: Add Property Widget to dashboard"'
        ReplaceRegex: '"DEV: Add Property Widget to dashboard"'
        UseUTF8: false
        UseRAW: true
    - task: PackageAzureDevOpsExtension@2
      inputs:
        rootFolder: '$(Build.SourcesDirectory)'
        publisherId: '$(PublisherId)'
        extensionId: '$(ExtensionId)'
        extensionVersion: '$(Build.BuildNumber)'
        extensionTag: '-DEV'
        updateTasksVersion: true
        extensionVisibility: 'private'
        extensionPricing: 'free'

# Continue with common tasks

#    - task: DeleteFiles@1
#      inputs:
#        SourceFolder: '$(Build.SourcesDirectory)\node_modules'
#        Contents: '**/*'
#        RemoveSourceFolder: true
#    - task: ArchiveFiles@2
#      inputs:
#        rootFolderOrFile: '$(Build.SourcesDirectory)'
#        includeRootFolder: false
#        archiveType: 'zip'
#        archiveFile: '$(Build.SourcesDirectory)/$(Build.DefinitionName)_$(Build.BuildNumber)_release.zip'
#        replaceExistingArchive: true
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          *.vsix
          *.zip
        TargetFolder: '$(Build.ArtifactStagingDirectory)/release'
        cleanTargetFolder: true
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)/release
        artifactName: release

# Publish DEV only in CI
    - task: PublishAzureDevOpsExtension@2
      inputs:
        connectTo: 'VsTeam'
        connectedServiceName: 'vs-marketplace-blockworks-com'
        fileType: 'vsix'
        vsixFile: '*-DEV*.vsix'
        extensionVisibility: 'private'
        extensionPricing: 'free'
        shareWith: 'dev2-blockworkscom'